# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(843, 699)
        Login.setStyleSheet("background-color: rgb(0, 74, 112);")
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setGeometry(QtCore.QRect(200, 190, 401, 381))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0,0.2);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.txtuser = QtWidgets.QLineEdit(self.frame)
        self.txtuser.setGeometry(QtCore.QRect(100, 90, 200, 40))
        self.txtuser.setMinimumSize(QtCore.QSize(200, 40))
        self.txtuser.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtuser.setFont(font)
        self.txtuser.setStyleSheet("color: rgb(255, 255, 255);")
        self.txtuser.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txtuser.setObjectName("txtuser")
        self.txtpass = QtWidgets.QLineEdit(self.frame)
        self.txtpass.setGeometry(QtCore.QRect(100, 190, 200, 40))
        self.txtpass.setMinimumSize(QtCore.QSize(200, 40))
        self.txtpass.setMaximumSize(QtCore.QSize(200, 40))
        self.txtpass.setStyleSheet("color: rgb(255, 255, 255);")
        self.txtpass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtpass.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txtpass.setObjectName("txtpass")
        self.btn_login = QtWidgets.QPushButton(self.frame)
        self.btn_login.setGeometry(QtCore.QRect(125, 270, 150, 40))
        self.btn_login.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_login.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_login.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_login.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(310, 80, 171, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(f"{os.getcwd()}\imagens\\icon_title.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label.raise_()
        self.frame.raise_()

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.txtuser.setPlaceholderText(_translate("Login", "Digite o usuário..."))
        self.txtpass.setPlaceholderText(_translate("Login", "Digite a senha..."))
        self.btn_login.setText(_translate("Login", "Entrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
