# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 724)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_home = QtWidgets.QPushButton(self.frame)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_home.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 80, 121);\n"
"    border-radius: 1px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color:back;\n"
"}")
        self.btn_home.setObjectName("btn_home")
        self.horizontalLayout.addWidget(self.btn_home)
        self.btn_tabelas = QtWidgets.QPushButton(self.frame)
        self.btn_tabelas.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_tabelas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_tabelas.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 80, 121);\n"
"    border-radius: 1px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color:back;\n"
"}")
        self.btn_tabelas.setObjectName("btn_tabelas")
        self.horizontalLayout.addWidget(self.btn_tabelas)
        self.btnc_importar = QtWidgets.QPushButton(self.frame)
        self.btnc_importar.setMinimumSize(QtCore.QSize(0, 35))
        self.btnc_importar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnc_importar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 80, 121);\n"
"    border-radius: 1px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color:back;\n"
"}")
        self.btnc_importar.setObjectName("btnc_importar")
        self.horizontalLayout.addWidget(self.btnc_importar)
        self.btn_carrinho = QtWidgets.QPushButton(self.frame)
        self.btn_carrinho.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_carrinho.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_carrinho.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 80, 121);\n"
"    border-radius: 1px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color:back;\n"
"}")
        self.btn_carrinho.setObjectName("btn_carrinho")
        self.horizontalLayout.addWidget(self.btn_carrinho)
        self.btn_contato = QtWidgets.QPushButton(self.frame)
        self.btn_contato.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_contato.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_contato.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 80, 121);\n"
"    border-radius: 1px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color:back;\n"
"}")
        self.btn_contato.setObjectName("btn_contato")
        self.horizontalLayout.addWidget(self.btn_contato)
        self.verticalLayout_2.addWidget(self.frame)
        self.Pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.Pages.setStyleSheet("background-color: rgb(0, 80, 121);")
        self.Pages.setObjectName("Pages")
        self.pag_table = QtWidgets.QWidget()
        self.pag_table.setObjectName("pag_table")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pag_table)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tables = QtWidgets.QTabWidget(self.pag_table)
        self.tables.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.tables.setObjectName("tables")
        self.Estoque = QtWidgets.QWidget()
        self.Estoque.setObjectName("Estoque")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Estoque)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.Estoque)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.txt_pes_prod = QtWidgets.QLineEdit(self.frame_4)
        self.txt_pes_prod.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_pes_prod.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.txt_pes_prod.setObjectName("txt_pes_prod")
        self.verticalLayout_13.addWidget(self.txt_pes_prod)
        self.table_estoque = QtWidgets.QTableWidget(self.frame_4)
        self.table_estoque.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_estoque.setObjectName("table_estoque")
        self.table_estoque.setColumnCount(8)
        self.table_estoque.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_estoque.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estoque.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estoque.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estoque.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estoque.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estoque.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estoque.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estoque.setHorizontalHeaderItem(7, item)
        self.table_estoque.horizontalHeader().setDefaultSectionSize(115)
        self.verticalLayout_13.addWidget(self.table_estoque)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btn_add_carrinho = QtWidgets.QPushButton(self.frame_8)
        self.btn_add_carrinho.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add_carrinho.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_add_carrinho.setObjectName("btn_add_carrinho")
        self.horizontalLayout_16.addWidget(self.btn_add_carrinho)
        self.btn_add_prod = QtWidgets.QPushButton(self.frame_8)
        self.btn_add_prod.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add_prod.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_add_prod.setObjectName("btn_add_prod")
        self.horizontalLayout_16.addWidget(self.btn_add_prod)
        self.btn_rem_prod = QtWidgets.QPushButton(self.frame_8)
        self.btn_rem_prod.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_rem_prod.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_rem_prod.setObjectName("btn_rem_prod")
        self.horizontalLayout_16.addWidget(self.btn_rem_prod)
        self.btn_alterar_prod = QtWidgets.QPushButton(self.frame_8)
        self.btn_alterar_prod.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_alterar_prod.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_alterar_prod.setObjectName("btn_alterar_prod")
        self.horizontalLayout_16.addWidget(self.btn_alterar_prod)
        self.btn_gerar_graf = QtWidgets.QPushButton(self.frame_8)
        self.btn_gerar_graf.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_gerar_graf.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_gerar_graf.setObjectName("btn_gerar_graf")
        self.horizontalLayout_16.addWidget(self.btn_gerar_graf)
        self.btn_gerar_excel = QtWidgets.QPushButton(self.frame_8)
        self.btn_gerar_excel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_gerar_excel.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_gerar_excel.setObjectName("btn_gerar_excel")
        self.horizontalLayout_16.addWidget(self.btn_gerar_excel)
        self.verticalLayout_13.addWidget(self.frame_8)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.tables.addTab(self.Estoque, "")
        self.Cliente = QtWidgets.QWidget()
        self.Cliente.setObjectName("Cliente")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Cliente)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.Cliente)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.txt_pesq_cliente = QtWidgets.QLineEdit(self.frame_2)
        self.txt_pesq_cliente.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_pesq_cliente.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.txt_pesq_cliente.setObjectName("txt_pesq_cliente")
        self.verticalLayout_9.addWidget(self.txt_pesq_cliente)
        self.table_cliente = QtWidgets.QTableWidget(self.frame_2)
        self.table_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_cliente.setObjectName("table_cliente")
        self.table_cliente.setColumnCount(8)
        self.table_cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cliente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cliente.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cliente.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cliente.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_cliente.setHorizontalHeaderItem(7, item)
        self.table_cliente.horizontalHeader().setDefaultSectionSize(115)
        self.verticalLayout_9.addWidget(self.table_cliente)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_add_client = QtWidgets.QPushButton(self.frame_9)
        self.btn_add_client.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add_client.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_add_client.setObjectName("btn_add_client")
        self.horizontalLayout_2.addWidget(self.btn_add_client)
        self.btn_remover_client = QtWidgets.QPushButton(self.frame_9)
        self.btn_remover_client.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_remover_client.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_remover_client.setObjectName("btn_remover_client")
        self.horizontalLayout_2.addWidget(self.btn_remover_client)
        self.btn_alterar_cliente = QtWidgets.QPushButton(self.frame_9)
        self.btn_alterar_cliente.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_alterar_cliente.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_alterar_cliente.setObjectName("btn_alterar_cliente")
        self.horizontalLayout_2.addWidget(self.btn_alterar_cliente)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.tables.addTab(self.Cliente, "")
        self.Fornecedor = QtWidgets.QWidget()
        self.Fornecedor.setObjectName("Fornecedor")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.Fornecedor)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.frame_11 = QtWidgets.QFrame(self.Fornecedor)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.txt_pesq_fornecedor = QtWidgets.QLineEdit(self.frame_11)
        self.txt_pesq_fornecedor.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_pesq_fornecedor.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.txt_pesq_fornecedor.setObjectName("txt_pesq_fornecedor")
        self.verticalLayout_20.addWidget(self.txt_pesq_fornecedor)
        self.table_fornecedor = QtWidgets.QTableWidget(self.frame_11)
        self.table_fornecedor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_fornecedor.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.table_fornecedor.setObjectName("table_fornecedor")
        self.table_fornecedor.setColumnCount(6)
        self.table_fornecedor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.table_fornecedor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fornecedor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fornecedor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fornecedor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fornecedor.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fornecedor.setHorizontalHeaderItem(5, item)
        self.table_fornecedor.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout_20.addWidget(self.table_fornecedor)
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.btn_add_forn = QtWidgets.QPushButton(self.frame_12)
        self.btn_add_forn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add_forn.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_add_forn.setObjectName("btn_add_forn")
        self.horizontalLayout_24.addWidget(self.btn_add_forn)
        self.btn_remover_forn = QtWidgets.QPushButton(self.frame_12)
        self.btn_remover_forn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_remover_forn.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_remover_forn.setObjectName("btn_remover_forn")
        self.horizontalLayout_24.addWidget(self.btn_remover_forn)
        self.btn_alterar_forn = QtWidgets.QPushButton(self.frame_12)
        self.btn_alterar_forn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_alterar_forn.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_alterar_forn.setObjectName("btn_alterar_forn")
        self.horizontalLayout_24.addWidget(self.btn_alterar_forn)
        self.verticalLayout_20.addWidget(self.frame_12)
        self.horizontalLayout_25.addWidget(self.frame_11)
        self.tables.addTab(self.Fornecedor, "")
        self.Vendas = QtWidgets.QWidget()
        self.Vendas.setObjectName("Vendas")
        self.frame_13 = QtWidgets.QFrame(self.Vendas)
        self.frame_13.setGeometry(QtCore.QRect(9, 9, 931, 581))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setGeometry(QtCore.QRect(-1, 0, 941, 591))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.txt_pesq_venda = QtWidgets.QLineEdit(self.frame_14)
        self.txt_pesq_venda.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_pesq_venda.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.txt_pesq_venda.setObjectName("txt_pesq_venda")
        self.verticalLayout_22.addWidget(self.txt_pesq_venda)
        self.table_venda = QtWidgets.QTableWidget(self.frame_14)
        self.table_venda.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_venda.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.table_venda.setObjectName("table_venda")
        self.table_venda.setColumnCount(7)
        self.table_venda.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.table_venda.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venda.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venda.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venda.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venda.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venda.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venda.setHorizontalHeaderItem(6, item)
        self.table_venda.horizontalHeader().setDefaultSectionSize(130)
        self.verticalLayout_22.addWidget(self.table_venda)
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.btn_remover_venda = QtWidgets.QPushButton(self.frame_15)
        self.btn_remover_venda.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_remover_venda.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_remover_venda.setObjectName("btn_remover_venda")
        self.horizontalLayout_34.addWidget(self.btn_remover_venda)
        self.btn_alterar_venda = QtWidgets.QPushButton(self.frame_15)
        self.btn_alterar_venda.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_alterar_venda.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_alterar_venda.setObjectName("btn_alterar_venda")
        self.horizontalLayout_34.addWidget(self.btn_alterar_venda)
        self.btn_gerargraf_venda = QtWidgets.QPushButton(self.frame_15)
        self.btn_gerargraf_venda.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_gerargraf_venda.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_gerargraf_venda.setObjectName("btn_gerargraf_venda")
        self.horizontalLayout_34.addWidget(self.btn_gerargraf_venda)
        self.btn_gerarexcel_venda = QtWidgets.QPushButton(self.frame_15)
        self.btn_gerarexcel_venda.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_gerarexcel_venda.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_gerarexcel_venda.setObjectName("btn_gerarexcel_venda")
        self.horizontalLayout_34.addWidget(self.btn_gerarexcel_venda)
        self.verticalLayout_22.addWidget(self.frame_15)
        self.tables.addTab(self.Vendas, "")
        self.verticalLayout_4.addWidget(self.tables)
        self.Pages.addWidget(self.pag_table)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_24 = QtWidgets.QLabel(self.page)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_33.addWidget(self.label_24)
        self.label_27 = QtWidgets.QLabel(self.page)
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_33.addWidget(self.label_27)
        self.label_25 = QtWidgets.QLabel(self.page)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_33.addWidget(self.label_25)
        self.verticalLayout_21.addLayout(self.horizontalLayout_33)
        self.label_31 = QtWidgets.QLabel(self.page)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_21.addWidget(self.label_31)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.pes_cnpj_forn = QtWidgets.QLineEdit(self.page)
        self.pes_cnpj_forn.setMaximumSize(QtCore.QSize(850, 16777215))
        self.pes_cnpj_forn.setStyleSheet("color: rgb(255, 255, 255);")
        self.pes_cnpj_forn.setObjectName("pes_cnpj_forn")
        self.horizontalLayout_26.addWidget(self.pes_cnpj_forn)
        self.btn_pes_cnpj = QtWidgets.QPushButton(self.page)
        self.btn_pes_cnpj.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_pes_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_pes_cnpj.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_pes_cnpj.setObjectName("btn_pes_cnpj")
        self.horizontalLayout_26.addWidget(self.btn_pes_cnpj)
        self.verticalLayout_21.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_19 = QtWidgets.QLabel(self.page)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_32.addWidget(self.label_19)
        self.frame_10 = QtWidgets.QFrame(self.page)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_22 = QtWidgets.QLabel(self.frame_10)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_27.addWidget(self.label_22)
        self.txt_cad_nome = QtWidgets.QLineEdit(self.frame_10)
        self.txt_cad_nome.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_cad_nome.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_cad_nome.setObjectName("txt_cad_nome")
        self.horizontalLayout_27.addWidget(self.txt_cad_nome)
        self.verticalLayout_14.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_30 = QtWidgets.QLabel(self.frame_10)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_31.addWidget(self.label_30)
        self.txt_cad_cnpj = QtWidgets.QLineEdit(self.frame_10)
        self.txt_cad_cnpj.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_cad_cnpj.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_cad_cnpj.setObjectName("txt_cad_cnpj")
        self.horizontalLayout_31.addWidget(self.txt_cad_cnpj)
        self.verticalLayout_14.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_29 = QtWidgets.QLabel(self.frame_10)
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_30.addWidget(self.label_29)
        self.txt_cad_telefone = QtWidgets.QLineEdit(self.frame_10)
        self.txt_cad_telefone.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_cad_telefone.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_cad_telefone.setObjectName("txt_cad_telefone")
        self.horizontalLayout_30.addWidget(self.txt_cad_telefone)
        self.verticalLayout_14.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_28.addWidget(self.label_26)
        self.txt_cad_email = QtWidgets.QLineEdit(self.frame_10)
        self.txt_cad_email.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_cad_email.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_cad_email.setObjectName("txt_cad_email")
        self.horizontalLayout_28.addWidget(self.txt_cad_email)
        self.verticalLayout_14.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_28 = QtWidgets.QLabel(self.frame_10)
        self.label_28.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_29.addWidget(self.label_28)
        self.txt_cad_site = QtWidgets.QLineEdit(self.frame_10)
        self.txt_cad_site.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_cad_site.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_cad_site.setObjectName("txt_cad_site")
        self.horizontalLayout_29.addWidget(self.txt_cad_site)
        self.verticalLayout_14.addLayout(self.horizontalLayout_29)
        self.frame_22 = QtWidgets.QFrame(self.frame_10)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.btn_cad_forn = QtWidgets.QPushButton(self.frame_22)
        self.btn_cad_forn.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_cad_forn.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_cad_forn.setFont(font)
        self.btn_cad_forn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_cad_forn.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_cad_forn.setObjectName("btn_cad_forn")
        self.horizontalLayout_41.addWidget(self.btn_cad_forn)
        self.verticalLayout_14.addWidget(self.frame_22)
        self.horizontalLayout_32.addWidget(self.frame_10)
        self.label_23 = QtWidgets.QLabel(self.page)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_32.addWidget(self.label_23)
        self.verticalLayout_21.addLayout(self.horizontalLayout_32)
        self.Pages.addWidget(self.page)
        self.pag_home = QtWidgets.QWidget()
        self.pag_home.setObjectName("pag_home")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pag_home)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home = QtWidgets.QLabel(self.pag_home)
        self.home.setStyleSheet("background-color: rgb(0, 80, 121);")
        self.home.setObjectName("home")
        self.verticalLayout.addWidget(self.home)
        self.Pages.addWidget(self.pag_home)
        self.page_xml = QtWidgets.QWidget()
        self.page_xml.setObjectName("page_xml")
        self.frame_6 = QtWidgets.QFrame(self.page_xml)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 871, 581))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.progressBar = QtWidgets.QProgressBar(self.frame_6)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_14.addWidget(self.progressBar)
        self.txt_selecionar_xml = QtWidgets.QLineEdit(self.frame_6)
        self.txt_selecionar_xml.setMinimumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_selecionar_xml.setFont(font)
        self.txt_selecionar_xml.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_selecionar_xml.setObjectName("txt_selecionar_xml")
        self.horizontalLayout_14.addWidget(self.txt_selecionar_xml)
        self.btn_open = QtWidgets.QPushButton(self.frame_6)
        self.btn_open.setMinimumSize(QtCore.QSize(120, 20))
        self.btn_open.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_open.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-top-rigth-radius: 15px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_14.addWidget(self.btn_open)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.frame_6)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.btn_importar_xml = QtWidgets.QPushButton(self.frame_6)
        self.btn_importar_xml.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_importar_xml.setFont(font)
        self.btn_importar_xml.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_importar_xml.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_importar_xml.setObjectName("btn_importar_xml")
        self.horizontalLayout_15.addWidget(self.btn_importar_xml)
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.Pages.addWidget(self.page_xml)
        self.page_contato = QtWidgets.QWidget()
        self.page_contato.setObjectName("page_contato")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.page_contato)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_20 = QtWidgets.QLabel(self.page_contato)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_11.addWidget(self.label_20)
        self.label_17 = QtWidgets.QLabel(self.page_contato)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.horizontalLayout_22.addLayout(self.verticalLayout_11)
        self.frame_7 = QtWidgets.QFrame(self.page_contato)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.img_insta = QtWidgets.QLabel(self.frame_7)
        self.img_insta.setMinimumSize(QtCore.QSize(25, 25))
        self.img_insta.setMaximumSize(QtCore.QSize(50, 50))
        self.img_insta.setObjectName("img_insta")
        self.horizontalLayout_17.addWidget(self.img_insta)
        self.btn_insta = QtWidgets.QCommandLinkButton(self.frame_7)
        self.btn_insta.setMinimumSize(QtCore.QSize(160, 50))
        self.btn_insta.setMaximumSize(QtCore.QSize(160, 50))
        self.btn_insta.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_insta.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_insta.setObjectName("btn_insta")
        self.horizontalLayout_17.addWidget(self.btn_insta)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.img_linkedin = QtWidgets.QLabel(self.frame_7)
        self.img_linkedin.setMaximumSize(QtCore.QSize(50, 50))
        self.img_linkedin.setObjectName("img_linkedin")
        self.horizontalLayout_18.addWidget(self.img_linkedin)
        self.btn_linkedin = QtWidgets.QCommandLinkButton(self.frame_7)
        self.btn_linkedin.setMinimumSize(QtCore.QSize(160, 50))
        self.btn_linkedin.setMaximumSize(QtCore.QSize(160, 50))
        self.btn_linkedin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_linkedin.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_linkedin.setObjectName("btn_linkedin")
        self.horizontalLayout_18.addWidget(self.btn_linkedin)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setMaximumSize(QtCore.QSize(50, 50))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_21.addWidget(self.label_18)
        self.btn_github = QtWidgets.QCommandLinkButton(self.frame_7)
        self.btn_github.setMinimumSize(QtCore.QSize(160, 50))
        self.btn_github.setMaximumSize(QtCore.QSize(160, 50))
        self.btn_github.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_github.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_github.setObjectName("btn_github")
        self.horizontalLayout_21.addWidget(self.btn_github)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.img_phone = QtWidgets.QLabel(self.frame_7)
        self.img_phone.setMaximumSize(QtCore.QSize(50, 50))
        self.img_phone.setObjectName("img_phone")
        self.horizontalLayout_20.addWidget(self.img_phone)
        self.btn_phone = QtWidgets.QCommandLinkButton(self.frame_7)
        self.btn_phone.setMinimumSize(QtCore.QSize(160, 50))
        self.btn_phone.setMaximumSize(QtCore.QSize(160, 50))
        self.btn_phone.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_phone.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_phone.setObjectName("btn_phone")
        self.horizontalLayout_20.addWidget(self.btn_phone)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22.addWidget(self.frame_7)
        self.Pages.addWidget(self.page_contato)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_16 = QtWidgets.QFrame(self.page_2)
        self.frame_16.setGeometry(QtCore.QRect(9, 19, 931, 591))
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_32 = QtWidgets.QLabel(self.frame_18)
        self.label_32.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_23.addWidget(self.label_32)
        self.txt_cliente_carrinho = QtWidgets.QLineEdit(self.frame_18)
        self.txt_cliente_carrinho.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.txt_cliente_carrinho.setObjectName("txt_cliente_carrinho")
        self.horizontalLayout_23.addWidget(self.txt_cliente_carrinho)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_33 = QtWidgets.QLabel(self.frame_18)
        self.label_33.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_35.addWidget(self.label_33)
        self.txt_vendedor_carrinho = QtWidgets.QLineEdit(self.frame_18)
        self.txt_vendedor_carrinho.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.txt_vendedor_carrinho.setObjectName("txt_vendedor_carrinho")
        self.horizontalLayout_35.addWidget(self.txt_vendedor_carrinho)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_35)
        self.verticalLayout_15.addWidget(self.frame_18)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_16)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.verticalLayout_15.addWidget(self.tableWidget)
        self.line = QtWidgets.QFrame(self.frame_16)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_15.addWidget(self.line)
        self.frame_19 = QtWidgets.QFrame(self.frame_16)
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_34 = QtWidgets.QLabel(self.frame_19)
        self.label_34.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_38.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_38.addWidget(self.label_35)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_19)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_38.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_19)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_38.addWidget(self.pushButton)
        self.label_36 = QtWidgets.QLabel(self.frame_19)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_38.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.frame_19)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_38.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.frame_19)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_38.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.frame_19)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_38.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.frame_19)
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_38.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.frame_19)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_38.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.frame_19)
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_38.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.frame_19)
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_38.addWidget(self.label_43)
        self.label_45 = QtWidgets.QLabel(self.frame_19)
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_38.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.frame_19)
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_38.addWidget(self.label_46)
        self.verticalLayout_15.addWidget(self.frame_19)
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.btn_realizar_venda_2 = QtWidgets.QPushButton(self.frame_17)
        self.btn_realizar_venda_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_realizar_venda_2.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_realizar_venda_2.setObjectName("btn_realizar_venda_2")
        self.horizontalLayout_37.addWidget(self.btn_realizar_venda_2)
        self.btn_rem_item_carrinho = QtWidgets.QPushButton(self.frame_17)
        self.btn_rem_item_carrinho.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_rem_item_carrinho.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_rem_item_carrinho.setObjectName("btn_rem_item_carrinho")
        self.horizontalLayout_37.addWidget(self.btn_rem_item_carrinho)
        self.btn_limpar_venda_carrinho = QtWidgets.QPushButton(self.frame_17)
        self.btn_limpar_venda_carrinho.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_limpar_venda_carrinho.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_limpar_venda_carrinho.setObjectName("btn_limpar_venda_carrinho")
        self.horizontalLayout_37.addWidget(self.btn_limpar_venda_carrinho)
        self.verticalLayout_15.addWidget(self.frame_17)
        self.Pages.addWidget(self.page_2)
        self.page_cad_prod = QtWidgets.QWidget()
        self.page_cad_prod.setObjectName("page_cad_prod")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.page_cad_prod)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.frame_23 = QtWidgets.QFrame(self.page_cad_prod)
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.frame_23)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_17.addWidget(self.label_8)
        self.label_47 = QtWidgets.QLabel(self.frame_23)
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.verticalLayout_17.addWidget(self.label_47)
        self.frame_5 = QtWidgets.QFrame(self.frame_23)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.txt_nome_prod = QtWidgets.QLineEdit(self.frame_5)
        self.txt_nome_prod.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_nome_prod.setObjectName("txt_nome_prod")
        self.horizontalLayout_9.addWidget(self.txt_nome_prod)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.txt_custo = QtWidgets.QLineEdit(self.frame_5)
        self.txt_custo.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_custo.setObjectName("txt_custo")
        self.horizontalLayout_10.addWidget(self.txt_custo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.txt_preco = QtWidgets.QLineEdit(self.frame_5)
        self.txt_preco.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_preco.setObjectName("txt_preco")
        self.horizontalLayout_12.addWidget(self.txt_preco)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.txt_qtd = QtWidgets.QLineEdit(self.frame_5)
        self.txt_qtd.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_qtd.setObjectName("txt_qtd")
        self.horizontalLayout_13.addWidget(self.txt_qtd)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.txt_fornecedor = QtWidgets.QLineEdit(self.frame_5)
        self.txt_fornecedor.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_fornecedor.setObjectName("txt_fornecedor")
        self.horizontalLayout_11.addWidget(self.txt_fornecedor)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.verticalLayout_17.addWidget(self.frame_5)
        self.frame_24 = QtWidgets.QFrame(self.frame_23)
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.btn_cad_prod = QtWidgets.QPushButton(self.frame_24)
        self.btn_cad_prod.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_cad_prod.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_cad_prod.setFont(font)
        self.btn_cad_prod.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_cad_prod.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_cad_prod.setObjectName("btn_cad_prod")
        self.horizontalLayout_43.addWidget(self.btn_cad_prod)
        self.verticalLayout_17.addWidget(self.frame_24)
        self.horizontalLayout_42.addWidget(self.frame_23)
        self.Pages.addWidget(self.page_cad_prod)
        self.pag_cadastro = QtWidgets.QWidget()
        self.pag_cadastro.setObjectName("pag_cadastro")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.pag_cadastro)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.frame_20 = QtWidgets.QFrame(self.pag_cadastro)
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label = QtWidgets.QLabel(self.frame_20)
        self.label.setObjectName("label")
        self.verticalLayout_16.addWidget(self.label)
        self.label_44 = QtWidgets.QLabel(self.frame_20)
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.verticalLayout_16.addWidget(self.label_44)
        self.frame_3 = QtWidgets.QFrame(self.frame_20)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.txt_nome = QtWidgets.QLineEdit(self.frame_3)
        self.txt_nome.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_nome.setObjectName("txt_nome")
        self.horizontalLayout_3.addWidget(self.txt_nome)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.txt_telefone = QtWidgets.QLineEdit(self.frame_3)
        self.txt_telefone.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_telefone.setObjectName("txt_telefone")
        self.horizontalLayout_4.addWidget(self.txt_telefone)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.txt_email = QtWidgets.QLineEdit(self.frame_3)
        self.txt_email.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_email.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_email.setObjectName("txt_email")
        self.horizontalLayout_5.addWidget(self.txt_email)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.txt_endereco = QtWidgets.QLineEdit(self.frame_3)
        self.txt_endereco.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_endereco.setObjectName("txt_endereco")
        self.horizontalLayout_8.addWidget(self.txt_endereco)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.txt_municipio = QtWidgets.QLineEdit(self.frame_3)
        self.txt_municipio.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_municipio.setObjectName("txt_municipio")
        self.horizontalLayout_7.addWidget(self.txt_municipio)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.txt_bairro = QtWidgets.QLineEdit(self.frame_3)
        self.txt_bairro.setMaximumSize(QtCore.QSize(850, 16777215))
        self.txt_bairro.setObjectName("txt_bairro")
        self.horizontalLayout_6.addWidget(self.txt_bairro)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_19.addWidget(self.label_21)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMaximumSize(QtCore.QSize(850, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_19.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.verticalLayout_16.addWidget(self.frame_3)
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.btn_cadastrar = QtWidgets.QPushButton(self.frame_21)
        self.btn_cadastrar.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_cadastrar.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_cadastrar.setFont(font)
        self.btn_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_cadastrar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_cadastrar.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,10);\n"
"    background-color: #fff;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170,255,255);\n"
"    color:back;\n"
"}")
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.horizontalLayout_39.addWidget(self.btn_cadastrar)
        self.verticalLayout_16.addWidget(self.frame_21)
        self.horizontalLayout_40.addWidget(self.frame_20)
        self.Pages.addWidget(self.pag_cadastro)
        self.verticalLayout_2.addWidget(self.Pages)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages.setCurrentIndex(2)
        self.tables.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_home.setText(_translate("MainWindow", "Home"))
        self.btn_tabelas.setText(_translate("MainWindow", "Tabelas"))
        self.btnc_importar.setText(_translate("MainWindow", "Importar"))
        self.btn_carrinho.setText(_translate("MainWindow", "Carrinho"))
        self.btn_contato.setText(_translate("MainWindow", "Contato"))
        self.txt_pes_prod.setPlaceholderText(_translate("MainWindow", "Pesquisar Produto..."))
        item = self.table_estoque.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.table_estoque.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.table_estoque.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Custo"))
        item = self.table_estoque.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Preço"))
        item = self.table_estoque.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Qtd. Estoque"))
        item = self.table_estoque.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Qtd. ideal"))
        item = self.table_estoque.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fornecedor"))
        item = self.table_estoque.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Necessidade"))
        self.btn_add_carrinho.setText(_translate("MainWindow", "Adicionar ao carrinho"))
        self.btn_add_prod.setText(_translate("MainWindow", "Adicionar produto"))
        self.btn_rem_prod.setText(_translate("MainWindow", "Remover produto"))
        self.btn_alterar_prod.setText(_translate("MainWindow", "Alterar Produto"))
        self.btn_gerar_graf.setText(_translate("MainWindow", "Gerar Gráfico"))
        self.btn_gerar_excel.setText(_translate("MainWindow", "Gerar Excel"))
        self.tables.setTabText(self.tables.indexOf(self.Estoque), _translate("MainWindow", "Estoque"))
        self.txt_pesq_cliente.setPlaceholderText(_translate("MainWindow", "Pesquisar Cliente..."))
        item = self.table_cliente.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_cliente.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.table_cliente.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Telefone"))
        item = self.table_cliente.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "E-mail"))
        item = self.table_cliente.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Endereço"))
        item = self.table_cliente.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Município"))
        item = self.table_cliente.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Bairro"))
        item = self.table_cliente.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "CPF"))
        self.btn_add_client.setText(_translate("MainWindow", "Cadastrar Cliente"))
        self.btn_remover_client.setText(_translate("MainWindow", "Remover Cliente"))
        self.btn_alterar_cliente.setText(_translate("MainWindow", "Alterar Cliente"))
        self.tables.setTabText(self.tables.indexOf(self.Cliente), _translate("MainWindow", "Clientes"))
        self.txt_pesq_fornecedor.setPlaceholderText(_translate("MainWindow", "Pesquisar Fornecedor..."))
        item = self.table_fornecedor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_fornecedor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.table_fornecedor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CNPJ"))
        item = self.table_fornecedor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Telefone"))
        item = self.table_fornecedor.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "E-mail"))
        item = self.table_fornecedor.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "WebSite"))
        self.btn_add_forn.setText(_translate("MainWindow", "Cadastrar Fornecedor"))
        self.btn_remover_forn.setText(_translate("MainWindow", "Remover Fornecedor"))
        self.btn_alterar_forn.setText(_translate("MainWindow", "Alterar Fornecedor"))
        self.tables.setTabText(self.tables.indexOf(self.Fornecedor), _translate("MainWindow", "Fornecedor"))
        self.txt_pesq_venda.setPlaceholderText(_translate("MainWindow", "Pesquisar Vendas..."))
        item = self.table_venda.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_venda.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Produto"))
        item = self.table_venda.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.table_venda.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Vendedor"))
        item = self.table_venda.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Quantidade"))
        item = self.table_venda.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Valor "))
        item = self.table_venda.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Data"))
        self.btn_remover_venda.setText(_translate("MainWindow", "Remover venda"))
        self.btn_alterar_venda.setText(_translate("MainWindow", "Alterar Venda"))
        self.btn_gerargraf_venda.setText(_translate("MainWindow", "Gerar Gráfico"))
        self.btn_gerarexcel_venda.setText(_translate("MainWindow", "Gerar Planilha"))
        self.tables.setTabText(self.tables.indexOf(self.Vendas), _translate("MainWindow", "Vendas"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#ffffff;\">Cadastrar Fornecedor</span></p></body></html>"))
        self.pes_cnpj_forn.setPlaceholderText(_translate("MainWindow", "Digite o CPNJ do fornecedor..."))
        self.btn_pes_cnpj.setText(_translate("MainWindow", "Pesquisar"))
        self.label_22.setText(_translate("MainWindow", "Nome"))
        self.label_30.setText(_translate("MainWindow", "CNPJ"))
        self.label_29.setText(_translate("MainWindow", "Telefone"))
        self.label_26.setText(_translate("MainWindow", "E-mail"))
        self.label_28.setText(_translate("MainWindow", "Site"))
        self.btn_cad_forn.setText(_translate("MainWindow", "Cadastrar"))
        self.home.setText(_translate("MainWindow", f"<html><head/><body><p align=\"center\"><img src=\"{os.getcwd()}\imagens\\rsz_2linha_alliance__divulgaÇÃo__mercedes-benz.png\"/></p><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">Sistema de gerenciamento</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">Importar XML</span></p></body></html>"))
        self.txt_selecionar_xml.setPlaceholderText(_translate("MainWindow", "Selecionar arquivo..."))
        self.btn_open.setText(_translate("MainWindow", "Abrir"))
        self.btn_importar_xml.setText(_translate("MainWindow", "IMPORTAR"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#ffffff;\">Desenvolvedor: Andrew Machado Dias de Jesus</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">Contatos</span></p></body></html>"))
        self.img_insta.setText(_translate("MainWindow", f"<html><head/><body><p align=\"center\"><img src=\"{os.getcwd()}\imagens\\instagram.png\"/></p></body></html>"))
        self.btn_insta.setText(_translate("MainWindow", "INSTAGRAM"))
        self.img_linkedin.setText(_translate("MainWindow", f"<html><head/><body><p><img src=\"{os.getcwd()}\imagens\\icons8-linkedin-circundado-30.png\"/></p></body></html>"))
        self.btn_linkedin.setText(_translate("MainWindow", "LINKEDIN"))
        self.label_18.setText(_translate("MainWindow", f"<html><head/><body><p><img src=\"{os.getcwd()}\imagens\\icons8-github-32.png\"/></p></body></html>"))
        self.btn_github.setText(_translate("MainWindow", "GITHUB"))
        self.img_phone.setText(_translate("MainWindow", f"<html><head/><body><p><img src=\"{os.getcwd()}\imagens\\phone.png\"/></p></body></html>"))
        self.btn_phone.setText(_translate("MainWindow", "(21)9 6956-5845"))
        self.label_32.setText(_translate("MainWindow", "Cliente"))
        self.label_33.setText(_translate("MainWindow", "Vendedor"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Produto"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Preço"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantidade"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fornecedor"))
        self.label_34.setText(_translate("MainWindow", "Valor total:"))
        self.label_35.setText(_translate("MainWindow", "R$"))
        self.pushButton.setText(_translate("MainWindow", "Atualizar valor"))
        self.btn_realizar_venda_2.setText(_translate("MainWindow", "Realizar Venda"))
        self.btn_rem_item_carrinho.setText(_translate("MainWindow", "Remover Item"))
        self.btn_limpar_venda_carrinho.setText(_translate("MainWindow", "Limpar venda"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">Cadastrar Produto</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Nome"))
        self.label_10.setText(_translate("MainWindow", "Custo"))
        self.label_11.setText(_translate("MainWindow", "Preço"))
        self.label_14.setText(_translate("MainWindow", "Quantidade"))
        self.label_12.setText(_translate("MainWindow", "Fornecedor"))
        self.btn_cad_prod.setText(_translate("MainWindow", "Cadastrar"))
        self.label.setText(_translate("MainWindow", f"<html><head/><body><p align=\"center\"><img src=\"{os.getcwd()}\imagens\\user.png\"><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">Cadastrar Cliente</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Nome</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Telefone</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">E-mail</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Endereço</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Município</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Bairro</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "CPF"))
        self.btn_cadastrar.setText(_translate("MainWindow", "Cadastrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
